Add PWA offline support for standalone web app install
meshtastic/web pull request #194
Opened 2024-05-09 01:50 UTC by stevenpovlitz

Addresses https://github.com/meshtastic/web/issues/182

This is my first PR to meshtastic and meshtastic/web, please point out contribution policies and conventions. The code is pulled from the default service worker setup from running:

```
npx create-react-app my-app --template cra-template-pwa-typescript
```

2024-05-09 01:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/web?pullRequest=194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/web?pullRequest=194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/web?pullRequest=194) it.</sub>

2024-05-09 01:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/web?pullRequest=194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/web?pullRequest=194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/web?pullRequest=194) it.</sub>

2025-01-30 18:35 UTC, dzienisz commented
I like this idea of making this app installable.

2025-02-19 14:15 UTC, danditomaso requested changes
This PR looks like its missing workbox-core being added to the package.json. As well it looks like it uses functions from workbox-core v3 instead of using the latest v4 version, functions such as `clientsClaim` doesn't exist in v4.

2025-02-27 10:25 UTC, KomelT commented
Closing this PR because this work was already merged in #468

2025-02-27 10:25 UTC, closed without merging