[Feature request]: Nodes quick options
meshtastic/web pull request #307
Opened 2024-09-18 09:35 UTC by KomelT

2024-09-18 17:32 UTC, Hunter275 commented
@KomelT 

The image you linked 404s

![image](https://github.com/user-attachments/assets/40ab1760-919f-4fa8-8cb7-91925f69b338)

2024-09-18 18:49 UTC, KomelT commented
@Hunter275 it is just gif of a feature. Now it should work.

2025-01-23 23:14 UTC, KomelT commented
This should be good to go if there aren't any more wishes.

2025-01-23 23:54 UTC, KomelT commented
@Hunter275 now it should be ready
![image](https://github.com/user-attachments/assets/656a11ce-792f-4801-b6cf-7ad5fb41e5bb)

2025-01-24 21:34 UTC, KomelT commented
This is latest.
![Screenshot_20250124_121025](https://github.com/user-attachments/assets/6024dc5e-56cd-4812-9b29-d903812652ee)

2025-01-30 17:09 UTC, KomelT commented
Screenshots of "Node Details"
![Screenshot_20250130_180659](https://github.com/user-attachments/assets/fe9d954e-d91d-4a7f-90de-55c8fc6892da)
![Screenshot_20250130_180712](https://github.com/user-attachments/assets/4a368840-705d-4ca7-ab3e-b55ca267aaaa)

2025-01-30 17:37 UTC, danditomaso requested changes

2025-01-30 17:37 UTC, danditomaso commented on src/components/generic/TimeAgo.tsx
> +const getTimeAgo = (timestamp: number): string => {
I'd prefer we avoid using setIntervals and manually calculating the time ago, we have a lib already in our package json for this called `timeago-react`. There is also the Browser API Intl which offers a built in api to calculate time ago, here is an article with some code you could re-use. 
https://dev.to/madsstoumann/showing-time-ago-in-a-social-feed-using-intlrelativetimeformat-5ceo

2025-01-30 17:44 UTC, danditomaso commented
I think there is also some issues with the time ago that is being calculated (any nodes that show "days ago")

![image](https://github.com/user-attachments/assets/e919424e-a133-40bf-8259-b924f7bb0dc3)

2025-02-02 13:09 UTC, KomelT commented on src/components/generic/TimeAgo.tsx
> +const getTimeAgo = (timestamp: number): string => {
I listened to your improvement and fixed code.

2025-02-02 14:32 UTC, KomelT commented on src/components/generic/TimeAgo.tsx
> +const getTimeAgo = (timestamp: number): string => {
@danditomaso

2025-02-03 16:54 UTC, danditomaso requested changes
See comments about useEffect usage

2025-02-03 16:54 UTC, danditomaso commented on src/components/generic/TimeAgo.tsx
> +  }, [timestamp]);
This useEffect doesn't make sense here, the timestamp will come into the function and be set to state after going through the getTimeAgo function, so what is the purpose of setting timestamp into state? 

The useEffect can be removed as its unnecessary. You can either add this in the body of the component

```
const timeAgo = getTimeAgo(timestamp)
``` 
 OR

```
  return <span>{getTimeAgo(timeAgo)}</span>;
```

2025-02-03 16:54 UTC, danditomaso commented on src/components/generic/Uptime.tsx
> +  }, [seconds]);
Same thing as above here

2025-02-03 16:54 UTC, danditomaso commented on src/components/PageComponents/Messages/TraceRoute.tsx
> +          <span key={i}>
As per the React documentation which specifically states not to use index as a key variable 
https://react.dev/learn/rendering-lists#why-does-react-need-keys 

What is wrong with using the nodeNum as the key?

2025-02-03 16:54 UTC, danditomaso commented on src/components/PageComponents/Messages/TraceRoute.tsx
> +            <span key={i}>
Same thing as above here.

2025-02-03 16:54 UTC, danditomaso commented on src/components/UI/Dialog.tsx
> +        "fixed z-50 grid w-full max-w-[512px] max-h-[100vh] overflow-y-scroll scale-100 gap-4 bg-white p-6 opacity-100 animate-in fade-in-90 slide-in-from-bottom-10 sm:max-w-lg sm:rounded-lg sm:zoom-
This is a smart addition!

2025-02-04 10:15 UTC, dzienisz commented
Let's match every mobile and web feature for consistency. If that is possible. But it would be nice to add a checklist for PRa to not forget to check is changes work on web and mobile.

2025-02-04 10:55 UTC, KomelT commented
@dzienisz like that https://github.com/meshtastic/web/issues/403 ?

2025-02-04 10:57 UTC, dzienisz commented
Yes! Like when it's UI/UX change it would be awesome to add before and after screenshots. Information it this was tested in the app, web and mobile view etc.

2025-02-04 17:12 UTC, danditomaso requested changes
Sorry I missed one of the useEffect's in src/components/Dialog/NodeDetailsDialog.tsx.  You should be able to remove it without a problem, and it will avoid extra re-renders due to setting the device to state

2025-02-04 17:12 UTC, danditomaso commented on src/components/Dialog/NodeDetailsDialog.tsx
> +  }, [nodeNumDetails, nodes]);
I think this useEffect isn't required either. Down on line 157 instead of wrapping <pre> {device} </pre> you could instead use <pre> {nodes.get(nodeNumDetails} </pre>. I dont think anything is gained by adding the device to state, other than adding one re-render.

2025-02-04 17:23 UTC, KomelT commented on src/components/Dialog/NodeDetailsDialog.tsx
> +  }, [nodeNumDetails, nodes]);
Fair, but I still need the device variable, because all other displayed value also uses it to reference the device.

I just removed the useEffect:
```typescript
...
  const { nodes } = useDevice();
  const { nodeNumDetails } = useAppStore();
  const device: Protobuf.Mesh.NodeInfo = nodes.get(nodeNumDetails);

  return device ? (
...
```

2025-02-04 17:35 UTC, danditomaso approved these changes

2025-02-18 15:54 UTC, KomelT commented
@danditomaso @Hunter275 I think this is ready for merge

2025-02-18 18:01 UTC, danditomaso commented on src/components/generic/DeviceImage.tsx
> +const hardwareModelToFilename: { [key: string]: string } = {
This doesn't have to change, but there is a helper that is a better way to handle hash tables in TS. The Record type could be used here <variable>: Record<string, string>

2025-02-18 18:02 UTC, merged

2025-02-18 18:02 UTC, danditomaso commented
@KomelT Its been merged, thanks for the contribution!