Bugfix/formwrapper fieldset
meshtastic/web pull request #327
Opened 2024-10-25 18:17 UTC by SebFox2011

2024-10-31 20:35 UTC, Hunter275 commented
@SebFox2011 please add a Description detailing what was done in this PR

2024-10-31 23:19 UTC, SebFox2011 commented
Sorry @Hunter275  I am not really famillar with github merge request. I have make some mistake. But for next i will enter a description. And i will start from master each time in my futurs mr

2024-10-31 23:20 UTC, Hunter275 commented
> Sorry @Hunter275  I am not really famillar with github merge request. I have make some mistake. But for next i will enter a description. And i will start from master each time in my futurs mr

Perfect, thank you for your contributions. I'll review these changes soon!

2025-01-24 21:22 UTC, danditomaso commented on .vscode/settings.json
> +  "stm32-for-vscode.armToolchainPath": false
Should this file be removed from the commit? I dont think .vscode settings should apply to everyone who uses this project.

2025-02-19 14:11 UTC, danditomaso requested changes
Once the .vscode settings.json changes are removed this is ready to be merged.

2025-02-27 13:27 UTC, closed without merging