Config page updates
meshtastic/web pull request #66
Opened 2023-01-01 08:34 UTC by GMart

I've added updated descriptions and options for module config pages and regular config pages. Also spelling corrections in those pages.

2023-01-01 13:33 UTC, sachaw requested changes
Looks great, thanks!

2023-01-01 13:33 UTC, sachaw commented on src/pages/Peers.tsx
> -                            success: "Recieved Metadata",
Could you please revert this change, I have some rework to this page uncommitted,  I'll fix it there

2023-01-02 03:45 UTC, GMart reviewed
Good to go for merge

2023-01-02 03:45 UTC, GMart commented on src/pages/Peers.tsx
> -                            success: "Recieved Metadata",
OK, reverted. I think you could have done a merge?

2023-01-02 08:40 UTC, merged